brew "atuin"
brew "fd"
brew "gh"
brew "jq"
brew "lazygit"
brew "lua-language-server"
brew "mise"
brew "neovim", args: ["HEAD"]
brew "ripgrep"
brew "skhd"
brew "vscode-langservers-extracted"
brew "vtsls"

cask "copilot-cli"
cask "firefox"
cask "ghostty"
cask "proton-drive"
cask "rectangle"
cask "scroll-reverser"

tap "asmvik/formulae"
