require("plugins.nord")
require("plugins.telescope")
require("plugins.lazygit")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.blink")
require("plugins.autopairs")

require("telescope").load_extension("file_browser")
require("telescope").load_extension("lazygit")
