require("plugins.autopairs")
require("plugins.blink")
require("plugins.format")
require("plugins.lazygit")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.nord")
require("plugins.telescope")
require("plugins.treesitter")

require("telescope").load_extension("file_browser")
require("telescope").load_extension("lazygit")
